### ISSUE TITLE
as admin:  can t delete users  

### ISSUE THREAD

**Issue by PimVermeeren** [IHIW/IHIW_Management#19] opened 2019-11-19 10:38 UTC
![image](https://user-images.githubusercontent.com/54659550/69139555-0958c580-0ac1-11ea-887f-a7ba835a3e71.png)

**Comment by Cornelieke-GenDx** [comment] 2019-11-19 10:39
The user is not deleted.

**Comment by espierin** [comment] 2019-11-20 08:37
Duplicate of #15 Users cannot be deleted. This item will be closed.

**Closed by espierin** 2019-11-20 08:37 UTC

**Comment by PimVermeeren** [comment] 2019-11-20 10:43
I still cant  delete users

Why did you close  it ??

Pim Vermeeren | System Administrator
GenDx | Yalelaan 48 | 3584 CM Utrecht | The Netherlands
Phone: +31 (0)30 252 3799  | p.vermeeren@gendx.com  | www.GenDx.com

Follow us [http://ruzius.nl/gendx.com/signture/twitter.png] <https://twitter.com/GenDx_HLA>  [http://ruzius.nl/gendx.com/signture/instagram.png] <https://www.instagram.com/gendx_hla/>  [http://ruzius.nl/gendx.com/signture/linkedin.png] <https://www.linkedin.com/company/795980?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A795980%2Cidx%3A2-1-2%2CtarId%3A1484563770372%2Ctas%3Agendx>

[https://www.gendx.com/signature/signatures/reply%20signature_gradient%20line.jpg]
